#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7B24DA8C9551659F (sguelton@redhat.com)
#
Name     : pypi-pythran
Version  : 0.12.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/99/e0/ed0e81de05cfa4ecbcbceec6603d175387d8bc7a6332cbfd155d09958ccf/pythran-0.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/99/e0/ed0e81de05cfa4ecbcbceec6603d175387d8bc7a6332cbfd155d09958ccf/pythran-0.12.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/99/e0/ed0e81de05cfa4ecbcbceec6603d175387d8bc7a6332cbfd155d09958ccf/pythran-0.12.0.tar.gz.asc
Summary  : Ahead of Time compiler for numeric kernels
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-pythran-bin = %{version}-%{release}
Requires: pypi-pythran-license = %{version}-%{release}
Requires: pypi-pythran-python = %{version}-%{release}
Requires: pypi-pythran-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(beniget)
BuildRequires : pypi(gast)
BuildRequires : pypi(numpy)
BuildRequires : pypi(ply)

%description
Pythran
#######
https://pythran.readthedocs.io
What is it?
-----------
Pythran is an ahead of time compiler for a subset of the Python language, with a
focus on scientific computing. It takes a Python module annotated with a few
interface descriptions and turns it into a native Python module with the same
interface, but (hopefully) faster.

%package bin
Summary: bin components for the pypi-pythran package.
Group: Binaries
Requires: pypi-pythran-license = %{version}-%{release}

%description bin
bin components for the pypi-pythran package.


%package license
Summary: license components for the pypi-pythran package.
Group: Default

%description license
license components for the pypi-pythran package.


%package python
Summary: python components for the pypi-pythran package.
Group: Default
Requires: pypi-pythran-python3 = %{version}-%{release}

%description python
python components for the pypi-pythran package.


%package python3
Summary: python3 components for the pypi-pythran package.
Group: Default
Requires: python3-core
Provides: pypi(pythran)
Requires: pypi(beniget)
Requires: pypi(gast)
Requires: pypi(numpy)
Requires: pypi(ply)

%description python3
python3 components for the pypi-pythran package.


%prep
%setup -q -n pythran-0.12.0
cd %{_builddir}/pythran-0.12.0
pushd ..
cp -a pythran-0.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664376160
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pythran
cp %{_builddir}/pythran-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pythran/6a7b1189c16283fa7f28dbdadda64777c82412a2 || :
cp %{_builddir}/pythran-%{version}/docs/LICENSE.rst %{buildroot}/usr/share/package-licenses/pypi-pythran/0fcc278a4a3d0341c919d405ce4a80f9c20f7c0c || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pythran
/usr/bin/pythran-config

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pythran/0fcc278a4a3d0341c919d405ce4a80f9c20f7c0c
/usr/share/package-licenses/pypi-pythran/6a7b1189c16283fa7f28dbdadda64777c82412a2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
